### ISSUE TITLE
Fatal error on beta branch

### ISSUE THREAD

**Issue by joehoyle** [humanmade/hm-platform#53]
We are getting the following error on Human Made site which is prevent cavalcade from running:

```
Feb 14 14:42:13 ip-172-32-29-42 cavalcade[2300]: PHP Warning:  require_once(./wp-includes/plugin.php): failed to open stream: No such file or directory in /srv/www/webroot/content/hm-platform/load.php on line 26
Feb 14 14:42:13 ip-172-32-29-42 cavalcade[2300]: PHP Fatal error:  require_once(): Failed opening required './wp-includes/plugin.php' (include_path='.:/usr/share/php') in /srv/www/webroot/content/hm-platform/load.php on line 26
```

**Comment by nathanielks** [comment]
I believe relevant scrollback is here:

https://hmn.slack.com/archives/C03GMNBH7/p1518433805000159
https://hmn.slack.com/archives/C03GMNBH7/p1518439220000279

**Comment by roborourke** [comment]
Is there any difference in how the cavalcade runner is called between `platform-docs` and `humanmade-production-v2`? I can see cavalcade jobs completed in the logs there and it's the same codebase. 

Also seeing completed jobs in the logs on chassis with that codebase. I thought I'd fixed the issue here: https://github.com/humanmade/hm-platform/blob/beta/load.php#L24

Will see if I can reproduce it locally.

**Comment by roborourke** [comment]
Not quite as satisfactory as I'd like but I updated the logic to get the real ABSPATH here: https://github.com/humanmade/hm-platform/blob/beta/load.php#L24

Working fine locally again, deploying to `platform-docs` to see if it's good there too. Weirdly I can't actually see anything in the PHP error logs or the cron logs for that stack.

**Comment by roborourke** [comment]
Running smoothly on `platform-docs` now

**Comment by roborourke** [comment]
Will need to update approach to cavalcade support once cavalcade runner has been updated.
